### ISSUE TITLE
Widget File

### ISSUE THREAD

**Issue by gnh632** [Esri/elevation-profile-template#18]
Hi,

I am trying to include this in the ESRI Web Appbuilder, but I am not seeing the widget file. Has this moved fully to the REST API, or is there a way to add this in as a widget? I tried grabbing the download from https://www.arcgis.com/home/item.html?id=b9d247c297f144459854751740f59f68. Neither 3.4 or 3.6 work. I believe this is due to Flash. 

Thanks for any details or help on this!
Garrett
[ReadMe.pdf](https://github.com/Esri/elevation-profile-template/files/4326570/ReadMe.pdf)
[Elevation_Profile_Widget_for_FV2.zip](https://github.com/Esri/elevation-profile-template/files/4326572/Elevation_Profile_Widget_for_FV2.zip)

**Comment by kellyhutchins** [comment]
The ArcGIS API for JavaScript version 3.x has an elevation profile widget you should be able to add to a WAB app. Details on the widget are here: https://developers.arcgis.com/javascript/3/jsapi/elevationprofile-amd.html

**Comment by gnh632** [comment]
Through that link, I think I found a more recent plug and play version: [https://community.esri.com/docs/DOC-3342-elevation-profile-widget-version-214-1232019](url). I am not the most versed in the dojo style of JavaScript. If you have additional information on that, I will look over that as well. Thanks for your quick response!
