### ISSUE TITLE
Pop-up hides elevation tracking icon

### ISSUE THREAD

**Issue by karmstro77** [Esri/elevation-profile-template#5]
When you select a feature on the map, the pop-up is displayed. The icon that tracks the location on the map of each elevation is hidden by the pop-up. Is it possible to not display the pop-up so it cannot hide the icon?
![elevationpopup](https://cloud.githubusercontent.com/assets/6819070/4532585/2fb9dba0-4d94-11e4-94db-d94a83f97599.png)

**Comment by kellyhutchins** [comment]
You can configure the app to disable popups.
