### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by arcebrito** [Esri/elevation-profile-template#6]
First of all, thanks for sharing your work, this is a very interesting widget.
I would like to know if there is a patch for the following issue: [Uncaught TypeError: Cannot read property 'length' of null], such messages appear on Chrome console's, and you know, this is a kind of error, which maybe do not affects the widget usability but still is there.

Could it be possible to have a new version without that issue? or could you tell me where do I need to scratch in?

![cannot_read_property_length_of_null](https://cloud.githubusercontent.com/assets/8278677/5038928/2011aa3a-6b5c-11e4-84ca-d71b22c8d093.png)

Thanks,
Arce Brito,

**Comment by kellyhutchins** [comment]
Thanks for reporting this. I'll take a look and see if we can get it resolved for a future release.

**Comment by arcebrito** [comment]
Thanks a for notify & solving the issue,

ArBr

2017-01-25 14:53 GMT-06:00 Kelly Hutchins <notifications@github.com>:
