### ISSUE TITLE
Elevation Widget @ CMV

### ISSUE THREAD

**Issue by goriliukasbuxton** [Esri/elevation-profile-template#7]
I added the Elevation Profile Widget to the CMV viewer. Arrow buttons and close button not displaying on the Measure Widget:
![measure_widget](https://cloud.githubusercontent.com/assets/8904086/6194359/aeb2a014-b391-11e4-8b84-dcd92c630efe.PNG)

**Comment by ERS-Long** [comment]
Hi, Have you figured out a solution for the CMV viewer, i am wanting to do the same thing, if you could show me some tip, that will be great. Thanks.

**Comment by kellyhutchins** [comment]
What is the CMV Viewer?

**Comment by ERS-Long** [comment]
https://github.com/cmv/cmv-app
 
it is a configurable js map viewer using esri js api

**Comment by goriliukasbuxton** [comment]
Almost the whole code section here:
https://github.com/cmv/cmv-app/issues/378

**Comment by kellyhutchins** [comment]
I don't have the time to take a look at integrating the elevation profile code into the CMV Viewer however I do have a simple sample that uses the Elevation Profile widget that may help you get your app up and running. 
In this sample we display the elevation profile chart after a user clicks on a link in a popup window. 
https://dl.dropboxusercontent.com/u/24627279/Viewer.zip

**Comment by ERS-Long** [comment]
Thanks.

is this the correct config for this widget

            measure: {
                include: true,
                id: 'measurement',
                type: 'titlePane',
                canFloat: true,
                path: 'widgets/ElevationsProfile',
                title: '<i class="icon-large
icon-flag"></i>&nbsp;&nbsp;Measurement',
                open: false,
                position: 5,
                placeAt: 'top', // right or left if type: titlePane, can
use top or bottom if type: contentPane
                options: {
                    map: true,
                    mapClickMode: true,
                    defaultAreaUnit: units.SQUARE_MILES,
                    defaultLengthUnit: units.MILES

                }
            },

somehow i always hit this error in the Widget.js file

            if ((!options.map) || (!options.profileTaskUrl) ||
(!options.scalebarUnits)) {

console.error(this.strings.errors.MissingConstructorParameters);

**Comment by ERS-Long** [comment]
Hi, got the widget sort of working, but there is an issue, it only works
the first time, after i disabled the tool, then if i tried it again, it
wont fire.

Please let me know if you have a solution for that or not.

Thanks.

**Comment by ERS-Long** [comment]
ok, figured it ou, i commented out

the following block in your code

then everything is working as normal

/*
        // SEND ERRORS TO THE CONSOLE //
        elevationsProfile.on("error", console.warn);
        // ENABLE/DISABLE MAP EVENTS WHEN USER IS DRAWING WITH MEASUREMENT
DISTANCE TOOL //
        elevationsProfile.on("measure-distance-checked", lang.hitch(this,
function (evt) {
            if (evt.checked) {
                connect.disconnect(this.clickEventHandle);
                this.clickEventHandle = null;
            } else {
                this.clickEventHandle = connect.connect(this.map,
"onClick", this.clickEventListener);
            }
        }));

*/

Thanks.

**Comment by goriliukasbuxton** [comment]
Cool,
Maybe you can commit the widget to the CMV community.

Cheers.

**Comment by ERS-Long** [comment]
will do.



On Thu, May 28, 2015 at 10:29 AM, goriliukasbuxton <notifications@github.com

**Comment by ERS-Long** [comment]
thank you.

**Comment by ERS-Long** [comment]
Hi,

Got the widget added to CMV user widget list.

Thanks.

Long

On Thu, May 28, 2015 at 10:29 AM, goriliukasbuxton <notifications@github.com
